#server:
#  port: 8080
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/sport_together
#    username: root
#    password: 1234
#
#  jpa:
#    database: mysql

 server:
   port: 8080

 spring:
   datasource:
     url: jdbc:mysql://localhost:3306/sport_together
     username: root
     password: 1234

   jpa:
     database: mysql


